const SLIME = {health: 2, energy: 1, score: 5};
const BAT= {health: 2.5, energy: 1, score: 10};
const SNAKE = {health: 3, energy: 1, score: 15};
const WOLF = {health: 4, energy: 1, score: 25};
const RAT= {health: 1, energy: 1, score: 7};
const FROG = {health: 2, energy: 1, score: 12};
const HAWK = {health: 2.5, energy: 1, score: 20};
const ROCK1 = {energy: 1, score: 5};
const ROCK2 = {energy :2, score: 15};
const ROCK3 = {energy :3, score: 30};
const BAG1 = {score: 10};
const BAG2= {score: 30};
const BAG3= {score: 100};
const SPIKE = {health: 4 , energy: 0}
const CHAINSAW = {health: 8, energy : 0}
const FIRE = { health: 3, energy :3};
const ACID = {health: 0, energy : 10};

const boardSize = { width: 25, height: 25 };
const obstacleAmount = boardSize.width * boardSize.height * 0.2;
const uiWidth = 160;
const navigationChance = 10;
const wallChance = 15;
const bagChance = 5;
const chestChance = 0.2;
const dollarChance = 2;
const potionChance = 1;
const healthPotionChance = 0.75;

const bombChance = 1.1;
const firecrackerChance = 0.75;
const droneChance = 1;
const lightningChance = 0.8;
const goggleChance = 0.4;

const spikeChance = 2.5;
const portalChance = 6;
const enemyChance = 8;
const fireChance = 5;
const acidChance = 3;

const getCanvas = document.getElementById("gameplay");
const getCanvas2 = document.getElementById("gameplayHUD");
const getCanvas3 = document.getElementById("gameplayHUD-right");

const grassImg = document.getElementById("grass");
const playerImg = document.getElementById("player");
const img_playerCry = document.getElementById("playerCry");
const img_rock = document.getElementById("rock");
const img_rock2 = document.getElementById("rock2");
const img_rock3 = document.getElementById("rock3");
const flagImg = document.getElementById("flag");
const wallImg = document.getElementById("wall");
const bagImg = document.getElementById("bag");
const directionImg = document.getElementById("arrow");
const img_potion_hp = document.getElementById("potionHealth");
const img_potion = document.getElementById("potionEnergy");
const img_treasureChest = document.getElementById("chest");
const img_bomb = document.getElementById("bomb");
const img_spikes = document.getElementById("spikes");
const img_firecracker = document.getElementById("firecracker");
const img_portal = document.getElementById("portal");
const img_portal2 = document.getElementById("portal2");
const img_portal3 = document.getElementById("portal3");
const img_enemy = document.getElementById("slime");
const img_enemy2 = document.getElementById("bat");
const img_enemy3 = document.getElementById("snake");
const img_enemy4 = document.getElementById("wolf");
const img_chainSaw = document.getElementById("chainsaw");
const img_dollar = document.getElementById("dollarBill");
const img_drone = document.getElementById("drone");
const img_lightning = document.getElementById("lightning");
const img_goggles = document.getElementById("goggles");
const img_frog = document.getElementById("frog");
const img_rat = document.getElementById("rat");
const img_hawk = document.getElementById("hawk");
const img_fire = document.getElementById("fire");
const img_acid = document.getElementById("acid");